---

- hosts: all
  become: true
  tasks:
  

  - name: remove apache2 package and add php support for apache.
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: absent
      update_cache: yes

