- name: "Check if unzip is installed"
  tags: validation
  package_facts:
    manager: "auto"

- name: "unzip test result"
  tags: validation
  debug: 
    msg: "unzip found"
  when: "'unzip' in ansible_facts.packages"

- name: "unzip test result"
  tags: validation
  debug: 
    msg: "unzip not found"
  when: "'unzip' not in ansible_facts.packages"
