- name: add ssh key for neo
  authorized_key:
    user: neo
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOJHRPh13gdbljDk1oMs8t7fDPi3fN8GpNr+Wll9HLxP ansible"
 
- name: Check for validation task
  tags: validation
  stat: 
    path: /home/alex/Documents/github/ansible_practice/roles/base/tasks/validate/{{ ansible_hostname }}.yml
  delegate_to: localhost
  register: validation_task


- include: validate/{{ ansible_hostname }}.yml
  tags: validation
  when: validation_task.stat.exists

